
downloads:
	wget -O public/doom.sqfs https://github.com/edubart/riv/releases/download/downloads/doom.sqfs
	wget -O public/rivemu.js https://github.com/edubart/riv/releases/download/downloads/rivemu.js
	wget -O public/rivemu.wasm https://github.com/edubart/riv/releases/download/downloads/rivemu.wasm
